@startuml

hide footbox
autonumber "<b>[0]</b>"

skinparam handwritten true

skinparam BoxPadding 10
skinparam ParticipantPadding 25

box "Java application"
participant App
participant NativeAPI
participant BluetoothConnection
participant Callback
end box

box "wrapper library"
participant Wrapper
participant WrappedCallback
end box

box "native library"
participant NativeLibrary
participant JavaConnection
end box

activate App

App -> App: doSomething
activate App

create Callback
App -> Callback: << create >>

App -> NativeAPI: method(callback)
activate NativeAPI

NativeAPI -> Wrapper: method(callback)
activate Wrapper

create WrappedCallback
Wrapper -> WrappedCallback: << create >>

Wrapper -> NativeLibrary: method(wrapper_callback)
activate NativeLibrary

loop isConversationCompleted = false
NativeLibrary -> JavaConnection: send/receive
activate JavaConnection

JavaConnection -> BluetoothConnection: send/receive
activate BluetoothConnection

BluetoothConnection --> JavaConnection
deactivate BluetoothConnection

JavaConnection --> NativeLibrary: << response >>
deactivate JavaConnection

NativeLibrary -> Wrapper: wrapper_callback
activate Wrapper

Wrapper -> WrappedCallback: operator()
activate WrappedCallback

WrappedCallback -> Callback: invoke
activate Callback

Callback --> WrappedCallback
deactivate Callback

WrappedCallback --> Wrapper
deactivate WrappedCallback

Wrapper --> NativeLibrary
deactivate Wrapper
end

NativeLibrary --> Wrapper: << response >>
deactivate NativeLibrary

Wrapper --> NativeAPI: << response >>
deactivate Wrapper

NativeAPI --> App: << response >>
deactivate NativeAPI
deactivate App

deactivate App

@enduml
