@startuml

skinparam handwritten true

namespace Java_application {

class NativeAPI {
  +method()
}
class BluetoothConnection {
  +isOpen()
  +open()
  +close()
  +send()
  +receive()
}
NativeAPI ..> BluetoothConnection
}

namespace wrapper_library {

class Wrapper << (-,orchid) >> #lavender {
  {static} +method()
}
}

namespace native_libary {

abstract class Connection {
  +send()
  +receive()
}

class BluetoothConnection
class SerialConnection
class JavaConnection #tomato
Connection <|-- BluetoothConnection
Connection <|-- SerialConnection
Connection <|-- JavaConnection

class Facade << (-,orchid) >> #lavender {
  {static} +method()
}
Facade ..> Connection
}

wrapper_library.Wrapper ..> native_libary.Facade
native_libary.JavaConnection o--> Java_application.BluetoothConnection
Java_application.NativeAPI ..> wrapper_library.Wrapper

' force layout
Java_application -[hidden]-> wrapper_library

@enduml