@startuml

skinparam handwritten true

namespace Java_application {

class NativeAPI {
  +method(callback)
}
class Callback {
  +invoke()
}
class BluetoothConnection {
  +isOpen()
  +open()
  +close()
  +send()
  +receive()
}
NativeAPI ..> Callback
NativeAPI ..> BluetoothConnection
}

namespace wrapper_library {

class Wrapper << (-,orchid) >> #lavender {
  {static} +method(callback)
  {static} -callback()
}

class WrappedCallback {
  +invoke()
}

Wrapper *--> WrappedCallback
}

namespace native_library {

class Facade << (-,orchid) >> #lavender {
  {static} +method(callback)
}

abstract class Connection {
  +send()
  +receive()
}

class JavaConnection #tomato

Connection <|-- BluetoothConnection
Connection <|-- SerialConnection
Connection <|-- JavaConnection

Facade ..> Connection
}

native_library.JavaConnection o--> Java_application.BluetoothConnection
wrapper_library.Wrapper ..> native_library.Facade
wrapper_library.WrappedCallback o--> Java_application.Callback
Java_application.NativeAPI ..> wrapper_library.Wrapper

' force layout
Java_application -[hidden]-> wrapper_library
Java_application -[hidden]-> wrapper_library

@enduml