@startuml
skinparam handwritten true
skinparam monochrome true
skinparam BoxPadding 32
skinparam dpi 96


box "My PC"
participant master
participant branch
end box
box "GitHub"
participant origin
participant remote #c0c0ff
end box

create origin
remote -> origin: fork
create master
origin -> master: clone
|||
master -> remote: remote add upstream
|||
create branch
master -> branch : checkout -b
branch -> branch: add, commit, ... *
opt fold commits
    branch -> branch: rebase -i <after-this-commit>\n... (see "Rebase - Interactive Mode")
end
branch -> origin: push
origin --> remote: <<open PR>>
|||
opt PR is accepted
    remote -> master: pull upstream master
    master -> origin: push
|||
end
@enduml